### PR TITLE
Update Graphical Calculator.py with fixed code

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
Since your `Graphical Calculator.py` was broken, here is a fix :).

### CODE REVIEW

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 Why was this PR closed? I believe it fixes the code.

**Comment by CodeMaster7000** [comment]
@SmashedFrenzy16 I had made other changes to the code too.

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 this one actually fixed the code. It would have saved you time.

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 but this fixes the code, which would save you time.

**Pull request closed without merging**
